export default [
  {
    id: 1,
    product: "Fusion",
    name: "Allen Solly",
    username: "shibi",
    email: "shibi@gmail.com",
    purchaseDate: "12-12-2022",
    adminAssigned: "Assigned",
    ExpireOn: "090 Dec 2022",
    RecurringEnabled: "No",
    TelegramUsername: "shibi",
    CanceledDate: "09 Nov 2022",
    reason: "hello irshad",
  },
  {
    id: 2,
    product: "Demo Fusion ",
    name: "Allen Solly",
    username: "shibi",
    email: "shibi@gmail.com",
    purchaseDate: "12-12-2022",
    adminAssigned: "Assigned",
    ExpireOn: "090 Dec 2022",
    RecurringEnabled: "No",
    TelegramUsername: "shibi",
    CanceledDate: "09 Nov 2022",
    reason: "hello irshad",
  },
];
